### ISSUE TITLE
Error trying to build "ProcessException: No such file or directory   Command: bower install -s"

### ISSUE THREAD

**Issue by Meai1** [polymer-dart/html5_demo#2]
Yes, I have bower installed, I always get this error:

```
[pc@localhost html5_demo]$ bazel build default
WARNING: Sandboxed execution is not supported on your system and thus hermeticity of actions cannot be guaranteed. See http://bazel.build/docs/bazel-user-manual.html#sandboxing for more information. You can turn off this warning via --ignore_unsupported_sandboxing.
INFO: Found 1 target...
ERROR: /home/pc/html5_demo/BUILD:26:1: Download JS dependencies with bower.json failed: polymerize failed: error executing command bazel-out/host/bin/external/polymerize_tool/polymerize bower -u bazel-out/local-fastbuild/bin/html5_demo.bower -u bazel-out/local-fastbuild/bin/external/html5/html5.bower -u ... (remaining 7 argument(s) skipped): com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 255.
Running bower with bazel-out/local-fastbuild/bin/bower.json
Downloading JS components
Unhandled exception:
ProcessException: No such file or directory
  Command: bower install -s
#0      runBowerMode.<runBowerMode_async_body> (package:polymerize/src/bower_command.dart:32)
#1      _asyncErrorWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:34)
#2      _RootZone.runBinary (dart:async/zone.dart:1410)
#3      _FutureListener.handleError (dart:async/future_impl.dart:146)
#4      _Future._propagateToListeners.handleError (dart:async/future_impl.dart:649)
#5      _Future._propagateToListeners (dart:async/future_impl.dart:671)
#6      _Future._completeError (dart:async/future_impl.dart:485)
#7      _Future._asyncCompleteError.<anonymous closure> (dart:async/future_impl.dart:537)
#8      _microtaskLoop (dart:async/schedule_microtask.dart:41)
#9      _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
#10     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:394)
#11     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:414)
#12     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)
Target //:default failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 0.500s, Critical Path: 0.32s
```

Btw... I did have this running once weeks ago when I first tried it. Did I see correctly that the output is like 500kb for this tiny hello world? That's kinda too much, am I wrong?

**Comment by dam0vm3nt** [comment]
The correct command to build this project is the one documented in the `README.md` : 

    bazel build html5_demo

Otherwise you get that error.

You can ignore it because is caused by the fact that this package has no bower dependencies thus the bower.json file is not generated (I'll add a fix to skip this step if bower.json is empty anyway, to avoid this kind of mistunderstanding).

For the size issue : that's due mostly by the whole dart runtime that's output for any project ( `dart_sdk.js` ). If you look at the actual generated file you will see they are very small.

I figure that the runtime will get splitted in the future to enable loading only the part we need, but for now we have to deal with it.

The good news is that you need to pay that price only once. So if you start adding your code you won't get the size raise proportionally.

**Comment by Meai1** [comment]
ok thanks, but I can't expect people to download 3-4 MB of javascript just to have the dart runtime. I looked up the size now, even 300-500KB would honestly be a tad painful.
